config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resource :comments
    resource :votes

    collection do
      get 'newest'
      get 'top'
      get 'controversial'
      get 'rising'
    end
  end

  resources :users
  resources :comments
  root to: 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :body, length: { minimum: 1 }

  def created_by?(user, post)
    return false if user.nil? || post.nil?
    user.id == self.user_id && post.id == self.post_id
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  
  validates :title, length: { minimum: 3 }, format: { with: /\A[A-Za-z]/ }

  def link
    return "/posts/#{id}" if url.nil?
    url
  end

  def score
    votes.sum(:value)
  end

  def hot_points
    (order + sign * epoch_seconds / 45000).round(7)
  end

  def controversy_score
    return 0 if up_votes <= 0 || down_votes <= 0
    magnitude ** balance
  end

  def has_already_voted? user, value
    return false if user.nil?
    self.votes.any?{|vote| vote.user_id == user.id && vote.value == value}
  end

  def created_by? user
    return false if user.nil?
    user.id == self.user_id
  end

  def up_votes
    self.votes.select{|vote| vote.value == 1 }.count
  end

  private
  def sign_from score
    return 0 if score == 0
    return 1 if score > 0
    -1
  end

  def down_votes
    self.votes.select{|vote| vote.value == -1 }.count
  end

  def magnitude
    up_votes + down_votes
  end

  def balance
    (up_votes > down_votes ) ? down_votes.to_f / up_votes : up_votes.to_f / down_votes
  end

  def order
    Math.log([1, self.score.abs].max,10)
  end

  def sign
    sign_from self.score
  end

  def epoch_seconds
    self.created_at.to_i - 1134028003
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, length: { minimum: 4 }, format: { with: /\A[A-Za-z]/ }, uniqueness: { case_sensitive: false }

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :value, inclusion: { in: [1, -1] } 
  validates :user_id, uniqueness: {scope: :post_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(params[:comment].permit(:body))
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Comment saved"
      redirect_to post_path(@post)
    else
      @comments = Post.find(params[:post_id]).comments
      @comment = Comment.new
      flash[:alert] = "Error: comments cannot be empty!"
      render 'posts/show'
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    flash[:notice] = "Comment deleted successfully"
    redirect_to post_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :newest, :top, :controversial, :rising]

  def index
    @posts = Post.all.sort_by(&:hot_points).reverse
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:title, :text, :url))
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Post created'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def newest
    @posts = Post.order(created_at: :desc)
    render 'index'
  end

  def top
    @posts = Post.all.sort_by(&:score).reverse
    render 'index'
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:notice] = "Post deleted successfully"
    redirect_to posts_path
  end

  def controversial
    @posts = Post.all.sort_by(&:controversy_score).reverse
    render 'index'
  end

  def rising
    @posts = Post.all.sort_by(&:up_votes).reverse
    render 'index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
    @comments = Comment.where(user_id: @user.id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    Vote.where(user_id: current_user.id, post_id: @post.id).first_or_initialize.update_attributes(value: params[:value])
    render json: { post_score:  @post.score }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_delete_link is_owner, comment
    is_owner ? link_to('delete', comment_path(comment, post_id: comment.post.id), method: :delete, class: 'delete-comment pull-right') : ''
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def comments_in_words(number)
    return 'no comments' if number < 1
    pluralize(number, 'comment')
  end

  def add_voting_colours(has_voted, original)
    has_voted ? original + ' selected' : original
  end

  def add_delete_link is_owner, post
    is_owner ? link_to('delete', post_path(post), method: :delete, class: 'delete-link pull-right') : ''
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/application/_header.html.haml
.navbar.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %a.navbar-brand{href: "/"} /not/reddit
    %ul.nav.navbar-nav
      %li.active
        = link_to 'Hot', posts_path
      %li
        = link_to 'New', newest_posts_path
      %li
        = link_to 'Rising', rising_posts_path
      %li
        = link_to 'Top', top_posts_path
      %li
        = link_to 'Controversial', controversial_posts_path
    %ul.nav.navbar-nav.pull-right
      - if user_signed_in?
        %li
          = link_to('Logout', destroy_user_session_path, method: :delete)
      - else
        %li
          = link_to('Login', new_user_session_path)
        %li
          = link_to('Register', new_user_registration_path)

app/views/comments/_comment.html.haml
%blockquote
  %p= comment.body
  %footer
    = link_to "#{comment.user.username}", user_path(comment.user.id) 
    #{time_ago_in_words(comment.created_at)} ago
    = comment_delete_link(comment.created_by?(current_user, comment.post), comment)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title /not/reddit
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'header'
    %section.notifications
      %p.bg-success= notice
      %p.bg-danger= alert
    %main.container
      = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/posts/_post.html.haml
%article.panel.post.col-md-8.col-sm-8.col-xs-8
  %section.votes
    = link_to post_votes_path(post, value: 1), class: add_voting_colours(post.has_already_voted?(current_user, 1),'vote-up') do
      %span.glyphicon.glyphicon-chevron-up
    %br
    %section.vote-score.badge
      = post.score
    %br
    = link_to post_votes_path(post, value: -1, user: current_user), class: add_voting_colours(post.has_already_voted?(current_user, -1),'vote-down') do
      %span.glyphicon.glyphicon-chevron-down
  %section.content
    %h4
      %a.post-link{href: post.link}= post.title
    %p= post.text
    %p.text-muted.small
      submitted #{time_ago_in_words(post.created_at)} ago by
      = link_to "#{post.user.username}", user_path(post.user.id)
    = link_to post_path(post), class: 'comment-text' do
      = comments_in_words(post.comments.count)
    = add_delete_link(post.created_by?(current_user), post)

app/views/posts/index.html.haml
%section.row
  = link_to 'New post', new_post_path, class: "col-md-4 col-sm-2 col-xs-2 pull-right"
  - if @posts.any?
    = render @posts
  - else
    %h2 No posts yet

app/views/posts/new.html.haml
- if @post.errors.any?
  The form has the following errors:
  %ul
    - @post.errors.full_messages.each do |msg|
      %li= msg
%h2 submit to notreddit
%ul.nav.nav-tabs#new-posts{role: "tablist"}
  %li.active
    %a{href: "#link", role: "tab", "data-toggle" => "tab"} Link Post
  %li
    %a{href: "#text", role: "tab", "data-toggle" => "tab"} Text Post
%section.tab-content
  %section.tab-pane.active#link
    = form_for @post do |f|
      %section.form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      %section.form-group
        = f.label :url
        = f.text_field :url, class: 'form-control'
      = f.submit 'Submit', id: 'submit-link', class: 'btn btn-default'
  %section.tab-pane#text
    = form_for @post do |f|
      %section.form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      %section.form-group
        = f.label :text
        = f.text_area :text, class: 'form-control'
      = f.submit 'Submit', id: 'submit-text', class: 'btn btn-default'

app/views/posts/show.html.haml
%section.row
  = render @post
- if current_user
  %section.row
    %section.post.col-md-10
      = form_for [@post, @comment] do |f|
        .hidden= f.label :body
        = f.text_area :body, size: "80x5"
        %br
        = f.submit 'Save'
%section.row
  %section.post.col-md-10
    - if @comments.any?
      %br
      = render @comments
    - else
      No comments yet

app/views/users/show.html.haml
%section.row
  %article.col-md-10.col-sm-10.col-xs-10
    %h2= @user.username
    %h6= "Joined #{time_ago_in_words(@user.created_at)} ago."
    %section.posts
      %h4
        %u Posts created
      = render @posts
      %br
%section.row.comments
  %article.col-md-10.col-sm-10.col-xs-10
    %h4
      %u Comments submitted
    = render @comments